# AAI614: Data Science & its Applications

*Notebook 2.4: Exploratory Data Analysis*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import subprocess
import pkg_resources

required = {'autoviz'}
installed = {pkg.key for pkg in pkg_resources.working_set}
missing = required - installed

if missing:
    python = sys.executable
    subprocess.check_call([python, '-m', 'pip', 'install', *missing], stdout=subprocess.DEVNULL)

import pandas as pd
import numpy as np
from autoviz import AutoViz_Class
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

/tmp/ipykernel_1238/3086438148.py:3: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)

In [2]:
students = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/students.csv")

##### If you don’t have a target variable you can leave it blank:

In [3]:
target_variable = 'Avg_Hours_Studied_per_week'

In [4]:
# @title Titre par défaut
AV = AutoViz_Class()
sep = ','


dft = AV.AutoViz(students, sep, depVar=target_variable, dfte="",
           header=0, verbose=1,
            lowess=False,chart_format='bokeh',max_rows_analyzed=500,max_cols_analyzed=30)

Shape of your Data Set loaded: (9, 6)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  2
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  2
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    5 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Student Name']

################ Multi_Classification problem #####################

WARNING:param.Scatter: Chart elements should only be supplied a single kdim
WARNING:param.Scatter:Chart elements should only be supplied a single kdim

Row
    [0] WidgetBox
        [0] Select(label='x', name='x', options=['Avg_Hours_Studied_per_we...], value='Avg_Hours_Studied_per_wee...)
        [1] Select(label='y', name='y', options=['GPA', 'Sense o...], value='GPA')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Row
    [0] WidgetBox
        [0] Select(label='X-Axis', name='X-Axis', options=['GPA', 'Sense o...], value='GPA')
        [1] Select(label='Y-Axis', name='Y-Axis', options=['GPA', 'Sense o...], value='Sense of Humour (0-5)')
        [2] Select(label='Color', name='Color', options=['None', 'Avg_Hours_Studie...], value='None')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(label='Select_categorical_var', options=[np.str_('University'), ...], value=np.str_('University'))

Column
    [0] Row
        [0] HoloViews(DynamicMap, height=400, sizing_mode='fixed', width=600)
        [1] WidgetBox(align=('end', 'start'))
            [0] Select(label='Select_numeric_variable', options=[np.str_('GPA'), ...], value=np.str_('GPA'))

KDE plot is erroring due to problems with DynamicMaps. Hence it is skipped

HoloViews(Layout)

No date vars could be found in data set

HoloViews(Overlay, height=500, sizing_mode='fixed', width=600)

Row
    [0] WidgetBox
        [0] Select(label='X-Axis', name='X-Axis', options=['University', ...], value='University')
        [1] Select(label='Y-Axis', name='Y-Axis', options=['GPA', 'Sense o...], value='GPA')
    [1] ParamFunction(function, _pane=HoloViews, defer_load=False)

Time to run AutoViz (in seconds) = 24

In [5]:
students.head()

,Student Name,Avg_Hours_Studied_per_week,GPA,University,Sense of Humour (0-5),Salary
0,George,20,NaN,NYU,3.0,$40k
1,Jerry,35,3.5,Columbia,5.0,$80k
2,Elaine,55,4.0,Columbia,4.2,$60k
3,Cosmo,5,2.0,City College,2.0,$25k
4,Newman,25,2.8,City College,0.0,$50k

In [6]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student Name                9 non-null      object
 1   Avg_Hours_Studied_per_week  9 non-null      int64
 2   GPA                         8 non-null      float64
 3   University                  9 non-null      object
 4   Sense of Humour (0-5)       7 non-null      float64
 5   Salary                      9 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 564.0+ bytes

In [7]:
students.describe()

       Avg_Hours_Studied_per_week     GPA    Sense of Humour (0-5)
count            9.000000          8.000000        7.000000
mean            37.777778          3.112500        2.271429
std             28.296545          0.716016        1.932800
min              5.000000          2.000000        0.000000
25%             20.000000          2.700000        0.850000
50%             35.000000          3.100000        2.000000
75%             50.000000          3.625000        3.600000
max            100.000000          4.000000        5.000000

In [8]:
students['University'].value_counts()

University
Columbia        3
Festivus Uni    3
City College    2
NYU             1
Name: count, dtype: int64

In [9]:
students['Salary'].describe()

count        9
unique       8
top       $40k
freq         2
Name: Salary, dtype: object

In [10]:
students['Sense of Humour (0-5)'].value_counts()

Sense of Humour (0-5)
0.0    2
3.0    1
5.0    1
4.2    1
2.0    1
1.7    1
Name: count, dtype: int64

In [11]:
students['University'].value_counts()

University
Columbia        3
Festivus Uni    3
City College    2
NYU             1
Name: count, dtype: int64

In [12]:
students['Salary_numeric'] = students['Salary'].str.replace('$', '').str.replace('k', '').astype(float)

In [13]:
students[['Avg_Hours_Studied_per_week', 'GPA',
          'Sense of Humour (0-5)', 'Salary_numeric']].corr()

,Avg_Hours_Studied_per_week,GPA,Sense of Humour (0-5),Salary_numeric
Avg_Hours_Studied_per_week,1.000000,0.593825,0.178640,-0.239747
GPA,0.593825,1.000000,0.686519,0.586421
Sense of Humour (0-5),0.178640,0.686519,1.000000,0.549761
Salary_numeric,-0.239747,0.586421,0.549761,1.000000